### PR TITLE
Preserve FdTables properly during a session fork.

### LINKED ISSUE #2592: Assertion `!is_monitoring(fd)' failed to hold. Task 154595 already monitoring fd 395
Using rr 94cf24c7, I see this crash:

```
0x00007fe28ac28100 in _start () from /lib64/ld-linux-x86-64.so.2
(rr) c
Continuing.
warning: Missing auto-load script at offset 0 in section .debug_gdb_scripts
of file /home/baku/Sources/m/dfpi/build/dist/bin/libxul.so.
Use `info auto-load python-scripts [REGEXP]' to list them.
### XPCOM_MEM_BLOAT_LOG defined -- logging bloat/leaks to /tmp/tmpIY52IZ/runtests_leaks_153878_tab_pid154443.log
[154443, Main Thread] WARNING: XPCOM_MEM_BLOAT_LOG is set, disabling native allocations.: file /home/baku/Sources/m/dfpi/src/tools/profiler/core/platform.cpp, line 224
Couldn't convert chrome URL: chrome://branding/locale/brand.properties
[Child 154443, Main Thread] WARNING: Could not get the program name for a cubeb stream.: 'NS_SUCCEEDED(rv)', file /home/baku/Sources/m/dfpi/src/dom/media/CubebUtils.cpp, line 375
1590471201737	Marionette	INFO	Listening on port 54883
[FATAL /home/baku/Sources/rr/src/FdTable.cc:25:add_monitor()] 
 (task 155959 (rec:154595) at time 142785)
 -> Assertion `!is_monitoring(fd)' failed to hold. Task 154595 already monitoring fd 395
Tail of trace dump:
{
  real_time:53308.943366 global_time:142765, event:`SYSCALLBUF_FLUSH' tid:154006, ticks:34312
  { syscall:'gettimeofday', ret:0x0, size:0x20 }
  { syscall:'gettimeofday', ret:0x0, size:0x20 }
  { syscall:'gettimeofday', ret:0x0, size:0x20 }
  { syscall:'futex', ret:0x0, size:0x14 }
}
{
  real_time:53308.943375 global_time:142766, event:`SYSCALL: futex' (state:ENTERING_SYSCALL) tid:154006, ticks:34312
rax:0xffffffffffffffda rbx:0xca rcx:0xffffffffffffffff rdx:0x0 rsi:0x189 rdi:0x7fb9cb013130 rbp:0x7fb9ca3fefa0 rsp:0x7fb9ca3fed90 r8:0x0 r9:0xffffffff r10:0x7fb9eac3fd08 r11:0x246 r12:0x7fb9cb01312c r13:0x7fb9cb00df50 r14:0x7fb9cb013130 r15:0x7fb9eac3fc50 rip:0x70000002 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xca fs_base:0x7fb9eac40700 gs_base:0x0
}
{
  real_time:53308.943381 global_time:142767, event:`SYSCALLBUF_RESET' tid:154006, ticks:34312
}
{
  real_time:53308.943457 global_time:142768, event:`SYSCALL: futex' (state:EXITING_SYSCALL) tid:154081, ticks:6082578
rax:0xffffffffffffff92 rbx:0xca rcx:0xffffffffffffffff rdx:0x0 rsi:0x89 rdi:0x7fb9c2afea08 rbp:0x7fb9c2ff9fa0 rsp:0x7fb9c2ff9d90 r8:0x0 r9:0xffffffff r10:0x7fb9c2afe8d8 r11:0x246 r12:0x7fb9c2afea04 r13:0x7fb9c2afe9a0 r14:0x7fb9c2afea08 r15:0x7fb9c2afe7c0 rip:0x70000002 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xca fs_base:0x7fb9c2aff700 gs_base:0x0
}
{
  real_time:53308.943683 global_time:142769, event:`SYSCALLBUF_FLUSH' tid:154081, ticks:6087036
  { syscall:'clock_gettime', ret:0x0, size:0x20 }
  { syscall:'futex', ret:0x0, size:0x14 }
  { syscall:'clock_gettime', ret:0x0, size:0x20 }
  { syscall:'gettid', ret:0x259e1, size:0x10 }
  { syscall:'clock_gettime', ret:0x0, size:0x20 }
  { syscall:'gettid', ret:0x259e1, size:0x10 }
  { syscall:'clock_gettime', ret:0x0, size:0x20 }
  { syscall:'clock_gettime', ret:0x0, size:0x20 }
  { syscall:'gettid', ret:0x259e1, size:0x10 }
  { syscall:'clock_gettime', ret:0x0, size:0x20 }
  { syscall:'gettid', ret:0x259e1, size:0x10 }
  { syscall:'clock_gettime', ret:0x0, size:0x20 }
  { syscall:'clock_gettime', ret:0x0, size:0x20 }
  { syscall:'clock_gettime', ret:0x0, size:0x20 }
  { syscall:'clock_gettime', ret:0x0, size:0x20 }
  { syscall:'clock_gettime', ret:0x0, size:0x20 }
  { syscall:'clock_gettime', ret:0x0, size:0x20 }
  { syscall:'clock_gettime', ret:0x0, size:0x20 }
  { syscall:'clock_gettime', ret:0x0, size:0x20 }
  { syscall:'clock_gettime', ret:0x0, size:0x20 }
  { syscall:'clock_gettime', ret:0x0, size:0x20 }
}
{
  real_time:53308.943692 global_time:142770, event:`SYSCALL: futex' (state:ENTERING_SYSCALL) tid:154081, ticks:6087036
rax:0xffffffffffffffda rbx:0xca rcx:0xffffffffffffffff rdx:0x0 rsi:0x89 rdi:0x7fb9c2afea08 rbp:0x7fb9c2ff9fa0 rsp:0x7fb9c2ff9d90 r8:0x0 r9:0xffffffff r10:0x7fb9c2afe8d8 r11:0x246 r12:0x7fb9c2afea04 r13:0x7fb9c2afe9a0 r14:0x7fb9c2afea08 r15:0x7fb9c2afe7c0 rip:0x70000002 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xca fs_base:0x7fb9c2aff700 gs_base:0x0
}
{
  real_time:53308.943699 global_time:142771, event:`SYSCALLBUF_RESET' tid:154081, ticks:6087036
}
{
  real_time:53308.943746 global_time:142772, event:`SYSCALL: futex' (state:EXITING_SYSCALL) tid:154019, ticks:1065236
rax:0xffffffffffffff92 rbx:0xca rcx:0xffffffffffffffff rdx:0x0 rsi:0x89 rdi:0x7fb9eba964a4 rbp:0x7fb9c67fbfa0 rsp:0x7fb9c67fbd90 r8:0x0 r9:0xffffffff r10:0x7fb9c6ffb0d0 r11:0x246 r12:0x7fb9eba9649c r13:0x7fb9eba96410 r14:0x7fb9eba964a4 r15:0x7fb9c6ffafe0 rip:0x70000002 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xca fs_base:0x7fb9c6ffc700 gs_base:0x0
}
{
  real_time:53308.943960 global_time:142773, event:`SYSCALLBUF_FLUSH' tid:154019, ticks:1068449
  { syscall:'clock_gettime', ret:0x0, size:0x20 }
  { syscall:'futex', ret:0x0, size:0x14 }
  { syscall:'clock_gettime', ret:0x0, size:0x20 }
  { syscall:'clock_gettime', ret:0x0, size:0x20 }
  { syscall:'clock_gettime', ret:0x0, size:0x20 }
}
{
  real_time:53308.943969 global_time:142774, event:`SYSCALL: futex' (state:ENTERING_SYSCALL) tid:154019, ticks:1068449
rax:0xffffffffffffffda rbx:0xca rcx:0xffffffffffffffff rdx:0x0 rsi:0x89 rdi:0x7fb9eba964a4 rbp:0x7fb9c67fbfa0 rsp:0x7fb9c67fbd90 r8:0x0 r9:0xffffffff r10:0x7fb9c6ffb0d0 r11:0x246 r12:0x7fb9eba9649c r13:0x7fb9eba96410 r14:0x7fb9eba964a4 r15:0x7fb9c6ffafe0 rip:0x70000002 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xca fs_base:0x7fb9c6ffc700 gs_base:0x0
}
{
  real_time:53308.943976 global_time:142775, event:`SYSCALLBUF_RESET' tid:154019, ticks:1068449
}
{
  real_time:53308.944170 global_time:142776, event:`SYSCALL: set_robust_list' (state:ENTERING_SYSCALL) tid:154595, ticks:133
rax:0xffffffffffffffda rbx:0x7fb7df2ff700 rcx:0xffffffffffffffff rdx:0xffffffffffffff30 rsi:0x18 rdi:0x7fb7df2ff9e0 rbp:0x0 rsp:0x7fb7df2feec0 r8:0x7fb7df2ff700 r9:0x7fb7df2ff700 r10:0x7fb7dfc5f496 r11:0x246 r12:0x7ffd317587be r13:0x7ffd317587bf r14:0x7ffd317587c0 r15:0x7fb7df2fef80 rip:0x7fb7dfc6459a eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x111 fs_base:0x7fb7df2ff700 gs_base:0x0
}
{
  real_time:53308.944212 global_time:142777, event:`SYSCALL: set_robust_list' (state:EXITING_SYSCALL) tid:154595, ticks:133
rax:0x0 rbx:0x7fb7df2ff700 rcx:0xffffffffffffffff rdx:0xffffffffffffff30 rsi:0x18 rdi:0x7fb7df2ff9e0 rbp:0x0 rsp:0x7fb7df2feec0 r8:0x7fb7df2ff700 r9:0x7fb7df2ff700 r10:0x7fb7dfc5f496 r11:0x246 r12:0x7ffd317587be r13:0x7ffd317587bf r14:0x7ffd317587c0 r15:0x7fb7df2fef80 rip:0x7fb7dfc6459a eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x111 fs_base:0x7fb7df2ff700 gs_base:0x0
}
{
  real_time:53308.944341 global_time:142778, event:`SYSCALL: gettid' (state:ENTERING_SYSCALL) tid:154595, ticks:284
rax:0xffffffffffffffda rbx:0x7fb7deafefa0 rcx:0xffffffffffffffff rdx:0x0 rsi:0x0 rdi:0x0 rbp:0x7fb7deafefa0 rsp:0x7fb7deafeda0 r8:0x0 r9:0x0 r10:0x0 r11:0x246 r12:0x7ffd317587be r13:0x7ffd317587bf r14:0x7ffd317587c0 r15:0x7fb7df2fef80 rip:0x70000005 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xba fs_base:0x7fb7df2ff700 gs_base:0x0
}
{
  real_time:53308.944381 global_time:142779, event:`SYSCALL: gettid' (state:EXITING_SYSCALL) tid:154595, ticks:284
rax:0x25be3 rbx:0x7fb7deafefa0 rcx:0xffffffffffffffff rdx:0x0 rsi:0x0 rdi:0x0 rbp:0x7fb7deafefa0 rsp:0x7fb7deafeda0 r8:0x0 r9:0x0 r10:0x0 r11:0x246 r12:0x7ffd317587be r13:0x7ffd317587bf r14:0x7ffd317587c0 r15:0x7fb7df2fef80 rip:0x70000005 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xba fs_base:0x7fb7df2ff700 gs_base:0x0
}
{
  real_time:53308.944504 global_time:142780, event:`SYSCALL: perf_event_open' (state:ENTERING_SYSCALL) tid:154595, ticks:284
rax:0xffffffffffffffda rbx:0x7fb7deafefa0 rcx:0xffffffffffffffff rdx:0xffffffffffffffff rsi:0x0 rdi:0x7fb7deafee70 rbp:0x7fb7deafefa0 rsp:0x7fb7deafeda0 r8:0x0 r9:0x0 r10:0xffffffffffffffff r11:0x246 r12:0x7fb7deafee70 r13:0x25be3 r14:0x7ffd317587c0 r15:0x7fb7df2fef80 rip:0x70000005 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x12a fs_base:0x7fb7df2ff700 gs_base:0x0
}
{
  real_time:53308.944553 global_time:142781, event:`SYSCALL: perf_event_open' (state:EXITING_SYSCALL) tid:154595, ticks:284
rax:0x4 rbx:0x7fb7deafefa0 rcx:0xffffffffffffffff rdx:0xffffffffffffffff rsi:0x0 rdi:0x7fb7deafee70 rbp:0x7fb7deafefa0 rsp:0x7fb7deafeda0 r8:0x0 r9:0x0 r10:0xffffffffffffffff r11:0x246 r12:0x7fb7deafee70 r13:0x25be3 r14:0x7ffd317587c0 r15:0x7fb7df2fef80 rip:0x70000005 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x12a fs_base:0x7fb7df2ff700 gs_base:0x0
}
{
  real_time:53308.944675 global_time:142782, event:`SYSCALL: fcntl' (state:ENTERING_SYSCALL) tid:154595, ticks:285
rax:0xffffffffffffffda rbx:0x4 rcx:0xffffffffffffffff rdx:0x64 rsi:0x406 rdi:0x4 rbp:0x7fb7deafefa0 rsp:0x7fb7deafed40 r8:0x0 r9:0x0 r10:0x0 r11:0x246 r12:0x7fb7deafee70 r13:0x25be3 r14:0x4 r15:0x7fb7df2fef80 rip:0x70000005 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x48 fs_base:0x7fb7df2ff700 gs_base:0x0
}
{
  real_time:53308.944728 global_time:142783, event:`SYSCALL: fcntl' (state:EXITING_SYSCALL) tid:154595, ticks:285
rax:0x65 rbx:0x4 rcx:0xffffffffffffffff rdx:0x64 rsi:0x406 rdi:0x4 rbp:0x7fb7deafefa0 rsp:0x7fb7deafed40 r8:0x0 r9:0x0 r10:0x0 r11:0x246 r12:0x7fb7deafee70 r13:0x25be3 r14:0x4 r15:0x7fb7df2fef80 rip:0x70000005 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x48 fs_base:0x7fb7df2ff700 gs_base:0x0
  { tid:154595, addr:0x7fb7dfca82ad, length:0x1 }
}
{
  real_time:53308.944854 global_time:142784, event:`SYSCALL: rrcall_init_buffers' (state:ENTERING_SYSCALL) tid:154595, ticks:290
rax:0xffffffffffffffda rbx:0x65 rcx:0xffffffffffffffff rdx:0x0 rsi:0x0 rdi:0x7fb7deafee70 rbp:0x7fb7deafefa0 rsp:0x7fb7deafeda0 r8:0x0 r9:0x0 r10:0x0 r11:0x246 r12:0x7fb7deafee70 r13:0x25be3 r14:0x4 r15:0x65 rip:0x70000005 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x3e9 fs_base:0x7fb7df2ff700 gs_base:0x0
}
{
  real_time:53308.945352 global_time:142785, event:`SYSCALL: rrcall_init_buffers' (state:EXITING_SYSCALL) tid:154595, ticks:290
rax:0x7fb7de7ff000 rbx:0x65 rcx:0xffffffffffffffff rdx:0x0 rsi:0x0 rdi:0x7fb7deafee70 rbp:0x7fb7deafefa0 rsp:0x7fb7deafeda0 r8:0x0 r9:0x0 r10:0x0 r11:0x246 r12:0x7fb7deafee70 r13:0x25be3 r14:0x4 r15:0x65 rip:0x70000005 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x3e9 fs_base:0x7fb7df2ff700 gs_base:0x0
  { map_file:"<ZERO>", addr:0x7fb7de7ff000, length:0x100000, prot_flags:"rw-s", file_offset:0x0, device:64769, inode:38020063, data_file:"", data_offset:0x0, file_size:0x100000 }
  { tid:154595, addr:0x7fb7dfca82ad, length:0x1 }
  { tid:154595, addr:0x7fb7dfca83d3, length:0x1 }
  { tid:154595, addr:0x7fb7deafee70, length:0x20 }
}
{
  real_time:53308.945523 global_time:142786, event:`SYSCALLBUF_FLUSH' tid:154595, ticks:896
  { syscall:'gettid', ret:0x25be3, size:0x10 }
}
=== Start rr backtrace:
rr(_ZN2rr13dump_rr_stackEv+0x5d)[0x55abe389480c]
rr(_ZN2rr9GdbServer15emergency_debugEPNS_4TaskE+0x1a6)[0x55abe36cc5d4]
rr(+0x382066)[0x55abe3701066]
rr(_ZN2rr21EmergencyDebugOstreamD1Ev+0x66)[0x55abe37012d0]
rr(_ZN2rr7FdTable11add_monitorEPNS_4TaskEiPNS_11FileMonitorE+0xcc)[0x55abe3696d56]
rr(_ZN2rr10ReplayTask17init_buffers_archINS_7X64ArchEEEvNS_10remote_ptrIvEE+0x33c)[0x55abe37fdfa0]
rr(_ZN2rr10ReplayTask12init_buffersENS_10remote_ptrIvEE+0x7a)[0x55abe37fcc98]
rr(+0x474ce8)[0x55abe37f3ce8]
rr(+0x478476)[0x55abe37f7476]
rr(+0x47566b)[0x55abe37f466b]
rr(+0x479fdb)[0x55abe37f8fdb]
rr(_ZN2rr19rep_process_syscallEPNS_10ReplayTaskEPNS_15ReplayTraceStepE+0x83)[0x55abe37f4717]
rr(_ZN2rr13ReplaySession28setup_replay_one_trace_frameEPNS_10ReplayTaskE+0x7ee)[0x55abe37eaf28]
rr(_ZN2rr13ReplaySession11replay_stepERKNS0_15StepConstraintsE+0xca)[0x55abe37eb220]
rr(_ZN2rr14ReplayTimeline19replay_step_forwardENS_10RunCommandEl+0x10a)[0x55abe38078e6]
rr(_ZN2rr9GdbServer14debug_one_stepERNS_10GdbRequestE+0x5a2)[0x55abe36c9798]
rr(_ZN2rr9GdbServer12serve_replayERKNS0_15ConnectionFlagsE+0x54f)[0x55abe36cb69f]
rr(+0x461e02)[0x55abe37e0e02]
rr(_ZN2rr13ReplayCommand3runERSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS7_EE+0x404)[0x55abe37e188c]
rr(main+0x21f)[0x55abe38b04eb]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3)[0x7f11efe260b3]
rr(_start+0x2e)[0x55abe362961e]
=== End rr backtrace
Launch gdb with
```

### PR DESCRIPTION
**Pull request by emilio**
As I understand it, this is not only about the fdtable sharing
relationships. Complete FdTables may have gotten lost if two threads
shared address spaces but not an FdTable (which AIUI can happen with
some exotic system calls, or with unshare() maybe?).

That's why I opted into eagerly cloning all fd tables during the fork
process, I don't know how we'd be able to preserve them properly
otherwise.

Fixes #2592

### CODE REVIEW

**Comment by khuey** [comment]
Hmm, I wonder if we're actually preserving complicated `CLONE_FILES` relationships correctly when we do checkpoints.

**Comment by emilio** [comment]
Right, we don't afaict. But I _think_ this patch should address it?

**Comment by khuey** [comment]
I haven't read the patch yet but I don't see how you would address it. If you have two threads that share an address space but not a file descriptor table, you can't recreate that exact relationship in a new set of two threads with clone(2) afaict (if you clone each of the original threads individually, you can't end up with two threads in a new address space together, and if you clone a leader and then clone a second one from that leader you'll lose one of the file descriptor tables).

**Comment by emilio** [comment]
Ah, I see. I think you're right. I thought you meant the case where the threads didn't share address space but shared fd tables.

For the case you're describing, my patch would cause the two `Task` objects to have two different `FdTable`s (so, same as before this patch), but the actual physical thread would still incorrectly share them, IIUC.

**Comment by emilio** [comment]
(That doesn't look like a regression though)

**Comment by khuey** [comment]
No, it's not, I'm just thinking aloud here.

**Comment by rocallahan** [comment]
During replay, which is the only mode where we support checkpoints currently, our tasks all have their own fd table in reality. See `prepare_clone` in `replay_syscall.cc`:
```
    // Block CLONE_THREAD/CLONE_FILES - during replay each task is its own
    // thread group/has its own fd table.
```
We only need to make sure the `FdTable` relationships are correct.

File: src/Session.cc [hunk 1]
```diff
@@ -607,11 +609,22 @@ static vector<uint8_t> capture_syscallbuf(const AddressSpace::Mapping& m,
   return clone_leader->read_mem(start, data_size);
 }
 
+static FdTable::shr_ptr get_or_clone_fd_table(
+    Task::ClonedFdTables& existing_clones, Task* task_to_clone) {
+  auto original_fd_table = task_to_clone->fd_table();
+  FdTable::shr_ptr& existing_clone =
+      existing_clones[uintptr_t(original_fd_table.get())];
+  if (!existing_clone)
+    existing_clone = original_fd_table->clone();
```
Comment (rocallahan) [inline src/Session.cc:618]: {} around if body.

File: src/test/mmap_fd_reuse_checkpoint.c [hunk 2]
```diff
@@ -0,0 +1,36 @@
+/* -*- Mode: C; tab-width: 8; c-basic-offset: 2; indent-tabs-mode: nil; -*- */
+
+#include "util.h"
+
+int gFd;
```
Comment (rocallahan) [inline src/test/mmap_fd_reuse_checkpoint.c:5]: just make this `static int fd`. We don't use this `g` stuff in rr :-).

**Review by rocallahan — CHANGES_REQUESTED** [review]
This looks great to me! Just those cosmetic fixes.

File: src/Session.cc (hunk 1 above)
Comment (emilio) [reply src/Session.cc:618]: Done.

File: src/test/mmap_fd_reuse_checkpoint.c (hunk 2 above)
Comment (emilio) [reply src/test/mmap_fd_reuse_checkpoint.c]: Hah, fun, that's one of the Gecko style rules I actually like, unlike the braces one ;)

Done anyhow :)

**Comment by rocallahan** [comment]
Thanks!!
