### PR TITLE
Fix various vfork issues

### LINKED ISSUE #2540: ReplaySession cloning scheme fails if vm and fd table do not match
Every once in a while I'm seeing reverse execution fail with an error message like:
```
[FATAL /home/keno/rr-clean/src/AutoRemoteSyscalls.cc:555:check_syscall_result()]
 (task 971134 (rec:923518) at time 4115775)
 -> Assertion `false' failed to hold. Syscall lseek failed with errno EBADF
```
with a backtrace like:
```
#15 0x000055a25709ab0d in rr::AutoRemoteSyscalls::check_syscall_result (this=0x7ffcd77d1550, ret=-9, syscallno=8) at /home/keno/rr-clean/src/AutoRemoteSyscalls.cc:555
#16 0x000055a25709e096 in rr::AutoRemoteSyscalls::infallible_syscall<int, long, int> (this=0x7ffcd77d1550, syscallno=8) at /home/keno/rr-clean/src/AutoRemoteSyscalls.h:160
#17 0x000055a25709a764 in rr::AutoRemoteSyscalls::infallible_lseek_syscall (this=0x7ffcd77d1550, fd=301, offset=0, whence=0) at /home/keno/rr-clean/src/AutoRemoteSyscalls.cc:539
#18 0x000055a257271c53 in rr::Task::copy_state (this=0x55a259e115a0, state=...) at /home/keno/rr-clean/src/Task.cc:2161
#19 0x000055a25724d1de in rr::Session::finish_initializing (this=0x55a25a0901d0)
```
I believe the issue is something like the following.
We select an arbitrary task in the AddressSpace to be the new group leader at clone time and then fork all other tasks that share the same address space from it. The problem with this is that we assume that all tasks within the same address space have the same file descriptor table. That is not necessarily the case (e.g. during vfork). As a result we fail to lseek the cloned data fd, because it doesn't exist in the incorrect fd table (or even if it does, it may not be the right one).

That said, the particular trace that I'm reproducing this in is quite long, so I haven't taken a very deep look yet, so my analysis may be wrong.

### PR DESCRIPTION
**Pull request by Keno**
This fixes #2540 and two other issues I found using the test I wrote for that issue. Details are in the commit messages, but the gist is that we need to rid ourselves of the assumption that FdTable/AddressSpace/ThreadGroups are all the same task set. I originally had a fourth commit that I thought was required, but turns out I had just written a bad test. I'm including it here for posterity. We might need it in the future, but at least for the moment, the code generated by the compiler seems to not cause issues (whereas including it might increase trace size unnecessarily and potentially cause unforeseen problems of its own).

```
commit 2e8ce978619d58991b826cdcf5fafbb560c26401
Author: Keno Fischer <keno@juliacomputing.com>
Date:   Thu May 7 02:51:21 2020 -0400

    Protect syscallbuf alt stack while in vfork

    The other task could smash it while we're not looking. While that
    task does have it's own syscallbuf alt stack, it will be running
    on the old task's alt stack as soon as it returns from the kernel.
    Whether or not that stack will be usable for a second return depends
    on the compiler, which we can't rely on.

diff --git a/src/record_syscall.cc b/src/record_syscall.cc
index d129608a..727f2a4f 100644
--- a/src/record_syscall.cc
+++ b/src/record_syscall.cc
@@ -2768,6 +2768,24 @@ static void prepare_clone(RecordTask* t, TaskSyscallState& syscall_state) {
     flags = SIGCHLD;
   }

+  // If we're vfork'ing, the two tasks will share the same stack. The libc
+  // is careful about not relying on the stack while inside vfork (not even
+  // for the return address), but the syscallbuf is not, so if we're in the
+  // syscallbuf, we need to protect our alt stack.
+  if (t->is_in_syscallbuf()) {
+    // Currently, we don't have a syscall hook that matches the libc clone.
+    // If we ever do, we'd have to handle that specially here.
+    ASSERT(t, flags & CLONE_VFORK);
+    remote_ptr<void> syscallbuf_stack_low = t->syscallbuf_alt_stack() - page_size();
+    remote_ptr<void> syscallbuf_stack_high = t->syscallbuf_alt_stack();
+    remote_ptr<void> sp = t->regs().sp();
+    ASSERT(t, syscallbuf_stack_low <= sp && sp <= syscallbuf_stack_high);
+    // The kernel doesn't look at this memory at all,
+    // so IN_OUT is a bit of a lie, but it has the correct behavior.
+    syscall_state.mem_ptr_parameter(syscallbuf_stack_low,
+      ParamSize(sp-syscallbuf_stack_low), IN_OUT);
+  }
+
```

### CODE REVIEW

File: src/Task.cc [hunk 1]
```diff
@@ -2114,10 +2114,14 @@ Task::CapturedState Task::capture_state() {
...
   state.desched_fd_child = desched_fd_child;
   state.cloned_file_data_fd_child = cloned_file_data_fd_child;
+  state.cloned_file_data_fname = cloned_file_data_fname;
   state.cloned_file_data_offset =
       cloned_file_data_fd_child >= 0
           ? get_fd_offset(this, cloned_file_data_fd_child)
           : 0;
+  if (state.cloned_file_data_fd_child) {
+
+  }
```
Comment (rocallahan) [inline src/Task.cc]: Pardon?

Comment (Keno) [reply src/Task.cc]: Ah, whoops. Rebase artifact. Will fix.

**Comment by rocallahan** [comment]
Reviewing individual commits in Github doesn't do what I want it to do. Anyway, looks good modulo the commit message fix ("remedy") and removing that migrated hunk.

**Comment by Keno** [comment]
Fixed!
