### PR TITLE
Better detection for running under rr

### LINKED ISSUE #2451: Assertion `nread == sizeof(val)' failed.
I'm seeing fairly frequent assertions failures of this kind:

```
rr: Saving execution to trace directory `/home/keno/.local/share/rr/julia-46'.
Test    (Worker) | Time (s) | GC (s) | GC % | Alloc (MB) | RSS (MB)
cmdlineargs  (1) |        started at 2020-03-09T16:53:05.521
rr: /home/keno/rr/src/PerfCounters.cc:275: int64_t rr::read_counter(rr::ScopedFd&): Assertion `nread == sizeof(val)' failed.
```

The thing that's probably unusual about this is that we're nesting `rr record` with `--ignore-nested`. It works fine (or rather I should say it doesn't assert) without the `--ignore-nested`. Doing this kind of thing used to work fine, a few months back, though of course both rr and the software I'm testing have changed since.

### PR DESCRIPTION
**Pull request by Keno**
As reported in #2451, if the RR_UNDER_RR environment variable does
not get passed down to the nested rr, said rr ignores the
`--ignore-nested` flags, because it assumes (wrongly) that it is
the top-level rr. To fix this, instead of relying on the environment
variable add another custom fake syscall (like the existing rrcalls
used by the preload library) that the inner rr can use to detect
whether or not it's being recorded.

Fixes #2451

### CODE REVIEW

File: src/record_syscall.cc [hunk 1]
```diff
@@ -4218,6 +4218,19 @@ static Switchable rec_prepare_syscall_arch(RecordTask* t,
...
       return PREVENT_SWITCH;
 
+    case SYS_rrcall_check_presence: {
+      // Since this is "user" facing, we follow best practices for regular
+      // syscalls and make sure that unused arguments (in this case all of them)
+      // are zero.
+      bool arguments_are_zero = true;
+      Registers r = t->regs();
+      for (int i = 1; i <= 6; ++i)
+        arguments_are_zero &= r.arg(i) == 0;
```
Comment (rocallahan) [inline src/record_syscall.cc]: {} around the `for` body please

File: src/util.cc [hunk 2]
```diff
@@ -1131,7 +1131,20 @@ double monotonic_now_sec() {
   return (double)tp.tv_sec + (double)tp.tv_nsec / 1e9;
 }
 
-bool running_under_rr() { return getenv("RUNNING_UNDER_RR") != NULL; }
+bool running_under_rr() {
+  static bool rr_under_rr, rr_check_done = false;
```
Comment (rocallahan) [inline src/util.cc]: separate declarations please.

File: src/util.cc [hunk 3]
```diff
@@ -1131,7 +1131,20 @@ double monotonic_now_sec() {
...
+  if (!rr_check_done) {
+    rr_check_done = true;
+    if (getenv("RUNNING_UNDER_RR") != NULL) {
```
Comment (rocallahan) [inline src/util.cc]: We might as well remove the `getenv` check, right? We should keep setting the variable, because it's easier for other apps/tools to check.

Comment (Keno) [reply src/util.cc]: Yep, we can remove it. I just kept it in case you thought it was useful to set this manually occasionally for testing.

**Comment by khuey** [comment]
This is only loosely related to the current commit, but the kernel is currently up to syscall number 438 (on amd64) so we're probably going to have to move the rr syscalls to new numbers shortly.

**Comment by rocallahan** [comment]
> we're probably going to have to move the rr syscalls to new numbers shortly.

That's a good point.

**Comment by rocallahan** [comment]
Thanks!
