### PR TITLE
Seccomp handling changes for Firefox's new sandbox

### LINKED ISSUE #1848: Firefox crashes under rr: "Bad system call"
I was trying to get a trace of Firefox. When e10s is enabled, the content process always crashes with SIGSYS. Here's the replay log:
```
$ rr replay -p plugin-container
ATTENTION: default value of option force_s3tc_enable overridden by environment.
GNU gdb (GDB) 7.12
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/yen/.local/share/rr/latest-trace/mmap_hardlink_625_plugin-container...done.
warning: File "/home/yen/Projects/mozilla-central/.gdbinit" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load".
To enable execution of this file add
        add-auto-load-safe-path /home/yen/Projects/mozilla-central/.gdbinit
line to your configuration file "/home/yen/.gdbinit".
To completely disable this security protection add
        set auto-load safe-path /
line to your configuration file "/home/yen/.gdbinit".
For more information about this security protection see the
"Auto-loading safe path" section in the GDB manual.  E.g., run from the shell:
        info "(gdb)Auto-loading safe path"
Really redefine built-in command "restart"? (y or n) [answered Y; input not from terminal]
>>> >>> >>> >>> ... ... >>> ... ... >>> ... ... ... 
>>> 
Remote debugging using :20898

--------------------------------------------------
 ---> Reached target process 20666 at event 6690.
--------------------------------------------------
warning: unable to open /proc file '/proc/20666/task/20666/maps'
warning: remote target does not support file transfer, attempting to access files from local filesystem.
Reading symbols from /lib64/ld-linux-x86-64.so.2...(no debugging symbols found)...done.
---Type <return> to continue, or q <return> to quit---
0x00007fd7a8ba4d70 in _start () from /lib64/ld-linux-x86-64.so.2
(rr) c
Continuing.
warning: Could not load shared library symbols for linux-vdso.so.1.
Do you need "set solib-search-path" or "set sysroot"?
warning: File "/home/yen/Projects/mozilla-central/obj-x86_64-pc-linux-gnu/toolkit/library/libxul.so-gdb.py" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load".
[New Thread 20666.20671]
[New Thread 20666.20688]
[New Thread 20666.20689]
[New Thread 20666.20690]
[New Thread 20666.20691]
[New Thread 20666.20692]
[New Thread 20666.20693]
[New Thread 20666.20694]
[New Thread 20666.20696]
[New Thread 20666.20697]
[New Thread 20666.20698]
[New Thread 20666.20705]
[New Thread 20666.20706]
[New Thread 20666.20707]
[New Thread 20666.20708]
[New Thread 20666.20710]
[New Thread 20666.20711]
[New Thread 20666.20712]
[New Thread 20666.20713]

Thread 1 received signal SIGSYS, Bad system call.
0x0000000070000005 in ?? ()
(rr) bt
#0  0x0000000070000005 in  ()
#1  0x00007fd7a897b018 in  () at /usr/bin/../lib/rr/librrpreload.so
#2  0x00007fd7a8978fe1 in  () at /usr/bin/../lib/rr/librrpreload.so
#3  0x00007fd7a897b04a in  () at /usr/bin/../lib/rr/librrpreload.so
(rr) info threads 
  Id   Target Id         Frame 
* 1    Thread 20666.20666 (Web Content) 0x0000000070000005 in ?? ()
  2    Thread 20666.20671 (Chrome_ChildThr) 0x0000000070000002 in ?? ()
  3    Thread 20666.20688 (JS Watchdog) 0x00007fd7a87674b8 in pthread_cond_timedwait@@GLIBC_2.3.2 ()
   from /usr/lib/libpthread.so.0
  4    Thread 20666.20689 (JS Helper) 0x00007fd7a876710f in pthread_cond_wait@@GLIBC_2.3.2 ()
   from /usr/lib/libpthread.so.0
  5    Thread 20666.20690 (JS Helper) 0x00007fd7a876710f in pthread_cond_wait@@GLIBC_2.3.2 ()
   from /usr/lib/libpthread.so.0
  6    Thread 20666.20691 (JS Helper) 0x00007fd7a876710f in pthread_cond_wait@@GLIBC_2.3.2 ()
   from /usr/lib/libpthread.so.0
  7    Thread 20666.20692 (JS Helper) 0x00007fd7a876710f in pthread_cond_wait@@GLIBC_2.3.2 ()
   from /usr/lib/libpthread.so.0
  8    Thread 20666.20693 (JS Helper) 0x00007fd7a876710f in pthread_cond_wait@@GLIBC_2.3.2 ()
   from /usr/lib/libpthread.so.0
  9    Thread 20666.20694 (Socket Thread) 0x000000007000000e in ?? ()
  10   Thread 20666.20696 (Hang Monitor) 0x00007fd7a876710f in pthread_cond_wait@@GLIBC_2.3.2 ()
   from /usr/lib/libpthread.so.0
  11   Thread 20666.20697 (BgHangManager) 0x00007fd7a876710f in pthread_cond_wait@@GLIBC_2.3.2 ()
   from /usr/lib/libpthread.so.0
  12   Thread 20666.20698 (Timer) 0x00007fd7a87674b8 in pthread_cond_timedwait@@GLIBC_2.3.2 ()
   from /usr/lib/libpthread.so.0
  13   Thread 20666.20705 (ImgDecoder #1) 0x00007fd7a876710f in pthread_cond_wait@@GLIBC_2.3.2 ()
   from /usr/lib/libpthread.so.0
  14   Thread 20666.20706 (ImgDecoder #2) 0x00007fd7a876710f in pthread_cond_wait@@GLIBC_2.3.2 ()
---Type <return> to continue, or q <return> to quit---
   from /usr/lib/libpthread.so.0
  15   Thread 20666.20707 (ImgDecoder #3) 0x00007fd7a876710f in pthread_cond_wait@@GLIBC_2.3.2 ()
   from /usr/lib/libpthread.so.0
  16   Thread 20666.20708 (ImageIO) 0x00007fd7a876710f in pthread_cond_wait@@GLIBC_2.3.2 ()
   from /usr/lib/libpthread.so.0
  17   Thread 20666.20710 (gmain) 0x000000007000000e in ?? ()
  18   Thread 20666.20711 (ImageBridgeChil) 0x00007fd7a876710f in pthread_cond_wait@@GLIBC_2.3.2 ()
   from /usr/lib/libpthread.so.0
  19   Thread 20666.20712 (threaded-ml) 0x000000007000000e in ?? ()
  20   Thread 20666.20713 (ProcessHangMoni) 0x00007fd7a876710f in pthread_cond_wait@@GLIBC_2.3.2 ()
   from /usr/lib/libpthread.so.0
(rr)
```
My environment:
* rr: 4.4.0.r10.g58fd04d-1
* Arch Linux x86_64
* Kernel 4.8.1
* Firefox: mozilla-central [f03e2740d604](https://hg.mozilla.org/mozilla-central/rev/f03e2740d604), built from source

### PR DESCRIPTION
**Pull request by khuey**
The first commit fixes a class of problems similar to `seccomp_veto_exec` (previously committed).  A seccomp trap skips executing the syscall but doesn't set the syscall return value to an error (it remains the syscall number).  All of our special handling code can't tell that the syscall didn't execute.  We can use `orig_rax` to communicate with it, but we can't use the value -1 because the kernel sets up signal delivery with that (and not doing the processing for sigreturn is bad).  -2 still skips the syscall in the seccomp trap, so we use that.

The second commit is a handy debugging assertion.

The third commit fixes #1848.  The approach suggested there is

> Maybe try this: in handle_seccomp_trap, if we're in an is_in_untraced_syscall, record syscall-enter and syscall-exit events for the syscall, then do an abort-commit like desched_state_changed does. Make stash_synthetic_sig push the signal to the front of the queue so it's sure to be processed next. Then in is_safe_to_deliver_signal, allow the signal to be delivered if it's our synthetic SIGSYS at an untraced syscall. That might be enough. The syscallbuf will be locked while the signal handler runs so we shouldn't have any reentrancy problems.
>
> Definitely test an untraced may-block syscall being interrupted by SIGSYS too. There may be some interaction with the desched logic ... we don't want to push a desched event while we're handling SIGSYS.

which is what is implemented.  `seccomp.c` tests `geteuid` and `open`, the latter of which tests the desched path.  The bits that are slightly hairy are the spurious SIGTRAP in preinject_signal that befuddles me and the intricate dance with the various bits of the syscallbuf we have to do.

### CODE REVIEW

File: src/SeccompFilterRewriter.h [hunk 1]
```diff
@@ -9,6 +9,8 @@
 #include <unordered_map>
 #include <vector>
 
+#define SECCOMP_MAGIC_SKIP_ORIGINAL_SYSCALLNO -2
```
Comment (rocallahan) [inline src/SeccompFilterRewriter.h]: Document what this means/is for
